### PR TITLE
remove numpy version requirements

### PR DESCRIPTION
**Pull request by ain-soph**
Is it possible to remove numpy version requirements?

I want to use the benchmark, but my codes are relying on some new bug fixes after `numpy>1.20`.

### CODE REVIEW

**Comment by D-X-Y** [comment]
Good question. I remember there are some conflicts between the higher-version numpy and the off-the-shelf benchmark files. But I can not remember the details, if you can also help resolve the above check failure issues, it may be ok.

**Comment by ain-soph** [comment]
The old `python setup.py install` will call `easy_install` instead of `pip` to install dependencies.

`easy_install` is already deprecated and it finds wrong numpy version. (1.22.3 for python 3.6, which can't be built).

**Comment by D-X-Y** [comment]
Oh, good to know that.

**Comment by D-X-Y** [comment]
Thanks for your contribution!

**Pull request merged**
